// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DisplayBoard","status":true,"description":"プラグインコマンドで自作の情報ボードを作成してWindow表示する","parameters":{}},
{"name":"ShareVariablesCounter","status":true,"description":"変数をユーザー共有のカウンタ化する","parameters":{"app_id":"guitarip5kotbe","start_variables_id":"1","end_variables_id":"10"}}
];
